"""
Configuration package for project settings.
"""

from .settings import *

__all__ = [
    "PROJECT_ROOT", "SRC_DIR", "DATA_DIR", "OUTPUT_DIR", "MODEL_DIR",
    "ACOUSTICBRAINZ_DIR", "JAMENDO_DIR", "RANDOM_SEED",
    "PCA_N_COMPONENTS", "PCA_EXPLAINED_VARIANCE_RATIO",
    "KMEANS_N_TOKENS", "KMEANS_N_CLUSTERS", "KMEANS_MAX_ITER", "KMEANS_N_INIT",
    "DL_N_NONZERO_COEFS", "DL_N_DICT_COMPONENTS", "DL_MAX_ITER", "DL_BATCH_SIZE",
    "T5_MODEL_NAME", "T5_MAX_LENGTH", "T5_UPSAMPLE_THRESHOLD", "T5_MAX_REPLICATION",
    "TRAIN_BATCH_SIZE", "EVAL_BATCH_SIZE", "LEARNING_RATE", "NUM_EPOCHS",
    "WARMUP_STEPS", "LOGGING_STEPS", "EVAL_STEPS", "SAVE_STEPS",
    "VISUALIZATION_SAMPLE_SIZE", "VISUALIZATION_N_TOP_TAGS"
]
